eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  datasource:
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  postgres:
    console:
      enabled: true
      
stripe:
  public_key: pk_test_51LRTtJLaaDb5UcZusRuQeNlxeshPsRvPYzvJU7JBhgZ8xMVmIW3tJmlo02Qks2zeyk7xsvHdUpdyuYTUweKWSYjx00f0M9h8SL
  secret_key: sk_test_51LRTtJLaaDb5UcZuDpnnOZjCbH1ic2xxba6VhdNvK8ntHSYg5hWBjq454w6vInfcng42SNTtpzsg03GfCC9CXHnh00VrYIzPNV

cloud_name: dsbuulrza
cloud_api_key: 571851636232923
cloud_api_secret: bLFS4abArQ3eQ7Dytw2SjSwaRec

spring:
  servlet:
    multipart:
      max-file-size: 7340032B
      max-request-size: 7340032B


